spring.application.name=smart-rdp

spring.datasource.url=jdbc:postgresql://localhost:5432/smartrdp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true

app.jwt.secret=c21hcnRyZHAtc2VjcmV0LWtleS1mb3ItaHMtMjU2LXNpZ25pbmctMjAyNi1kdW9jdWM=
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:4200

server.port=8080
